package by.bsuir.ovchelupov.lab1.task13;

import by.bsuir.ovchelupov.lab1.Scanner;

public class Runner {
    /**
     * Creates book by user input
     *
     * @return Book generated by user input
     */
    private static ProgrammerBook inputProgrammerBook() {
        String author;
        String title;
        int price;
        String isbn;
        String language;
        int level;
        var Scanner = new Scanner();
        System.out.print("Enter book title: ");
        title = Scanner.getString();
        System.out.print("Enter book author: ");
        author = Scanner.getString();
        System.out.print("Enter book price: ");
        price = Scanner.getNonNegativeInt();
        System.out.print("Enter book language: ");
        language = Scanner.getNonEmptyString();
        System.out.print("Enter book level: ");
        level = Scanner.getInt();
        System.out.print("Enter book isbn: ");
        isbn = Scanner.getString();

        return new ProgrammerBook(title, author, price, isbn, language, level);
    }

    /**
     * Entry point for program
     *
     * @param args CLI arguments, not in use
     */
    public static void main(String[] args) {
        ProgrammerBook book1;
        ProgrammerBook book2;

        System.out.println("Fill book 1 info");
        book1 = inputProgrammerBook();
        System.out.println("Fill book 2 info");
        book2 = inputProgrammerBook();
        var Scanner = new Scanner();

        System.out.print("Enter book edition: ");
        by.bsuir.ovchelupov.lab1.task12.Book.setEdition(Scanner.getNonNegativeInt());

        System.out.println("Are books equal? " + book1.equals(book2));

        System.out.println("Books hash codes:");
        System.out.println("\tBook 1: " + book1.hashCode());
        System.out.println("\tBook 2: " + book2.hashCode());

        System.out.println("Books string representation:");
        System.out.println("\tBook 1: " + book1.toString());
        System.out.println("\tBook 2: " + book2.toString());
    }

    /**
     * Constructor to avoid object creation
     */
    private Runner() {
    }
}