package by.bsuir.ovchelupov.task15;

import by.bsuir.ovchelupov.Scanner;
import by.bsuir.ovchelupov.task12.Book;

import java.util.ArrayList;
import java.util.Comparator;

/**
 * Class to show implementation of task 15
 */
public class Runner {

    private Runner() {
    }

    /**
     * Creates book by user input
     *
     * @return Book generated by user input
     */
    private static Book getBookFromInputBook() {
        String author, title, isbn;
        int price;
        var scanner = new Scanner();
        System.out.print("Enter book title: ");
        title = scanner.getString();
        System.out.print("Enter book author: ");
        author = scanner.getString();
        System.out.print("Enter book price: ");
        price = scanner.getNonNegativeInt();
        System.out.print("Enter book ISBN: ");
        isbn = scanner.getString();

        return new Book(title, author, price, isbn);
    }

    /**
     * Creates list of all comparators to show
     *
     * @return List of all comparators to show
     */
    private static ArrayList<Comparator<Book>> getComparators() {
        ArrayList<Comparator<Book>> comparators = new ArrayList<>();

        comparators.add(new BookTitleComparator());
        comparators.add(new BookTitleAuthorComparator());
        comparators.add(new BookAuthorTitleComparator());
        comparators.add(new BookAuthorTitlePriceComparator());
        return comparators;
    }

    /**
     * Entry point for program
     *
     * @param args CLI arguments, not in use
     */
    public static void main(String[] args) {
        ArrayList<Book> bookList = new ArrayList<>();
        int booksCount;
        ArrayList<Comparator<Book>> comparators = getComparators();

        System.out.print("Enter number of books to sort: ");
        var scanner = new Scanner();
        booksCount = scanner.getNonNegativeInt();

        for (int i = 0; i < booksCount; i++) {
            try {
                System.out.println("Enter book " + (i + 1) + " out of " + booksCount + " info");
                bookList.add(getBookFromInputBook());
            } catch (IllegalArgumentException e) {
                System.out.println("Input error: " + e.getMessage());
                i--;
            }
        }

        for (Comparator<Book> comparator : comparators) {
            bookList.sort(comparator);
            System.out.println("Books sorted by " + comparator.toString().replaceAll("\\w+\\.", "")
                    + ": ");
            System.out.println('\t' + bookList.toString());
        }
    }
}
