package by.bsuir.ovchelupov.task13.runner;

import by.bsuir.ovchelupov.task13.task.ProgrammerBook;
import by.bsuir.ovchelupov.utils.Scanner;
import by.bsuir.ovchelupov.task12.task.Book;

public class Runner {

    /**
     * Creates book by user input
     *
     * @return Book generated by user input
     */
    private static ProgrammerBook inputAndCreateProgrammerBook() {
        String author;
        String title;
        int price;
        String isbn;

        String language;
        int level;

        var scanner = new Scanner();
        System.out.print("Enter book title: ");
        title = scanner.getString();

        System.out.print("Enter book author: ");
        author = scanner.getString();

        System.out.print("Enter book price: ");
        price = scanner.getNonNegativeInt();

        System.out.print("Enter book language: ");
        language = scanner.getNonEmptyString();

        System.out.print("Enter book level: ");
        level = scanner.getInt();

        System.out.print("Enter book isbn: ");
        isbn = scanner.getString();

        return new ProgrammerBook(title, author, price, isbn, language, level);
    }

    /**
     * Starts the application
     *
     * @param args CLI arguments, not in use
     */
    public static void main(String[] args) {
        ProgrammerBook book1;
        ProgrammerBook book2;

        System.out.println("Fill book 1 info");
        book1 = inputAndCreateProgrammerBook();

        System.out.println("Fill book 2 info");
        book2 = inputAndCreateProgrammerBook();

        var Scanner = new Scanner();
        System.out.print("Enter book edition: ");
        Book.setEdition(Scanner.getNonNegativeInt());

        System.out.println("Are books equal? " + book1.equals(book2));

        System.out.println("Books hash codes:");
        System.out.println("\tBook 1: " + book1.hashCode());
        System.out.println("\tBook 2: " + book2.hashCode());

        System.out.println("Books string representation:");
        System.out.println("\tBook 1: " + book1.toString());
        System.out.println("\tBook 2: " + book2.toString());
    }

    /**
     * Constructor to avoid object creation
     */
    private Runner() {
    }
}